/* eslint-disable */
// This file is auto-generated by graphql-codegen
// Run `npm run codegen` to regenerate

export function graphql(source: string) {
  return source;
}

// Placeholder types until codegen runs
export type FragmentType<T> = T;
export function useFragment<T>(_fragment: T, data: T): T {
  return data;
}
